package com.wwgroup.flow.bo;

public enum WorkStage {

	CREATE, INNERJOINTSIGN, CHENGHE, JOINTSIGN, CONFIRM, CANCEL, REJECT, BOSS_SIGN, COPYDEPT, CENTER_CHENGHE, CMPCODEJOINTSIGN, FBOSS_SIGN,DIVISION_SIGN,CENTERJOINTSIGN,DEPT_CHENGHE,BUSINESS_SIGN,FBUSINESS_SIGN,SYSTEMJOINTSIGN,FCHENGHE,XZJOINTSIGN,CHAIRMAN_SIGN,SubmitFBoss_SIGN, BOSSPLUS_SIGN

}
